FROM alpine

# This can be overridden from command line e.g. docker run hello newhello
#CMD [ "echo", "Hello" ] 

# On the other hand this can't be overridden. arguments get appended e.g. docker run hello newhello
ENTRYPOINT [ "python", "HelloWorld.py" ] 